name: movie_db_data
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.0.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  path_provider: ^2.0.12
  retrofit: ^4.0.1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  retrofit_generator: ^5.0.0
  very_good_analysis: ^4.0.0

flutter:

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
